### ISSUE TITLE
vuetify入れたけど使い方わからん

### ISSUE THREAD

**Issue by ihch** [nemusou/summer-diary#7]
こんなんがいっぱい出る
```
 error  in ./node_modules/vuetify/src/components/VDataTable/VVirtualTable.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/nemu_sou/Projects/summer-diary/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/nemu_sou/Projects/summer-diary/node_modules/sass-loader/dist/index.js:36:28)
```

**Comment by ihch** [comment]
`@types/node` を入れる感じでした
